x-web: &web
  container_name: portfolio
  restart: always
  tty: true
  stdin_open: true
  env_file:
   - .env
  ports:
    - "${WEB_PORT}:${WEB_PORT}"

services:
  redis:
    container_name: portfolio-redis
    image: bitnami/redis:latest
    restart: always
    tty: true
    stdin_open: true
    user: root
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      REDIS_PORT_NUMBER: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./.docker/redis:/bitnami/redis
    profiles:
      - dev
      - ''
  web-dev:
    <<: *web
    user: root
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - dev
      - ''
  web-prod:
    <<: *web
    image: izakdvlpr/izakdvlpr.com:latest
    profiles:
      - prod

networks:
  default:
    name: portfolio
    driver: bridge